# Generated by Django 5.1.1 on 2024-09-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_pruduct_description_pruduct_volume_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pruduct',
            new_name='product',
        ),
    ]
